version: "3.9"
services:
  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - .:/app
    links:
      - database
  nginx:
    image: nginx:1.19.6
    links:
      - php
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/simatc.conf:/etc/nginx/conf.d/simatc.conf
  database:
    image: mariadb:10.5.8-focal
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simatc
    ports:
      - 3306:3306
