version: "3.9"
services:
  php:
    image: php:8.0.1-fpm-buster
    command: php -S 0.0.0.0:80
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 80:80
  composer:
    image: composer:2.0.8
    command: install
    working_dir: /app
    volumes_from:
      - php