version: "3.9"
services:
  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - .:/app
  composer:
    image: composer:2.0.8
    command: install
    working_dir: /app
    volumes_from:
      - php
  nginx:
    image: nginx:1.19.6
    links:
      - php
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/simatc.conf:/etc/nginx/conf.d/simatc.conf